### PR TITLE
Bump dwn-sdk-js to v0.2.6

### PR DESCRIPTION
**Pull request by diehuxx**

### CODE REVIEW

**Comment by amika-sq** [comment]
@diehuxx do you know if anything changed in the latest dwn release that might be causing this? https://github.com/TBD54566975/dwn-sql-store/actions/runs/6738388710/job/18317854886?pr=9

I did a quick look, and it doesn't seem like anything of note changed with our signing algorithms. Will take a closer look into what might be the cause here 🤔

**Comment by diehuxx** [comment]
@amika-sq No changes AFAIK to signing algorithms. We made some changes to where we put the JWS in the DWN message, but that should be orthogonal / wouldn't likely produce that error message.

**Comment by diehuxx** [comment]
Seems like a circular dependency issue that arose as a result of this PR. https://github.com/TBD54566975/dwn-sdk-js/pull/591. We are importing from `index.js` in `ed25519.ts`.

I'll put a up a PR in dwn-sdk-js fixing and bumping the dwn-sdk-js version.

**Review by LiranCohen — APPROVED** [review]
🚀

**Pull request merged**
