### PR TITLE
More permissive requirements for readble-stream and multiformats deps

### PR DESCRIPTION
**Pull request by amika-sq**
Came about when pulling in this library in the wallet mobile app, and a PR comment here: https://github.com/TBD54566975/web5-wallet/pull/44#discussion_r1273961453

In all honesty, I'm not sure if this is a good idea or not. Just wanted to propose it and get some feedback!

### CODE REVIEW

**Comment by mistermoe** [comment]
@amika-sq is this so that `dwn-sdk-js` and `dwn-sql-store` use the same version of those two dependencies?

**Comment by amika-sq** [comment]
> @amika-sq is this so that dwn-sdk-js and dwn-sql-store use the same version of those two dependencies?

Yup, that's the idea I believe. 

I've been thinking about this, and I'm curious if this is common practice for javascript libraries or not. On one hand, it does allow consumers of the library to only pull in one version of transient dependencies. 

But on the other hand, it seems super dangerous. Package owners of `readable-stream` and `multiformats` could, at any time, introduce a change in a point release that makes our library incompatible with it.

**Review by thehenrytsai — APPROVED** [review]

**Comment by thehenrytsai** [comment]
@amika-sq, I preferred to lock to reduce foot gun situation, but this ask has been surfaced multiple times by multiple devs, it is clear that it is hindering in some cases thus am fine opening it up to give it a go.

**Comment by thehenrytsai** [comment]
Closing due to inactivity.

**Pull request closed without merging**
